export const GET_COMPANIES_FETCHING = 'SHOW_COMPANIES_FETCHING';
export const GET_COMPANIES_FULFILLED = 'SHOW_COMPANIES_FULFILLED';
export const GET_COMPANIES_REJECTED = 'SHOW_COMPANIES_REJECTED';

export const ADD_COMPANY_FETCHING = 'ADD_COMPANY_FETCHING';
export const ADD_COMPANY_FULFILLED = 'ADD_COMPANY_FULFILLED';
export const ADD_COMPANY_REJECTED = 'ADD_COMPANY_REJECTED';

export const EDIT_COMPANY_FETCHING = 'EDIT_COMPANY_FETCHING';
export const EDIT_COMPANY_FULFILLED = 'EDIT_COMPANY_FULFILLED';
export const EDIT_COMPANY_REJECTED = 'EDIT_COMPANY_REJECTED';

export const DELETE_COMPANY_FETCHING = 'DELETE_COMPANY_FETCHING';
export const DELETE_COMPANY_FULFILLED = 'DELETE_COMPANY_FULFILLED';
export const DELETE_COMPANY_REJECTED = 'DELETE_COMPANY_REJECTED';